#' Apply EMA Crossover Buy/Sell Engine
#'
#' This function applies an Exponential Moving Average (EMA) crossover strategy to a given set of stock data.
#' It calculates the EMA based on specified parameters for fast and slow EMAs and generates buy/sell signals
#' and Hold states based on these EMAs. The function returns the stock data augmented with EMA values,
#' signals, and Hold states.
#'
#' Signal = {-1, 0 ,1} generated by end of time (t)
#' Execution = {-1, 0, 1} generated by end of time (t) + lag
#' Hold = {1, 0} assume hold position from (t+1) + lag to sell signal at time (t)
#' buy signal(t) then buy at ATO(t+1) then sell signal(t) then sell at ATO(t+1)
#'
#'
#'
#' @param stock_data A data frame or xts object containing stock data, must include a 'Close' column.
#' @param ema_fast_param Integer specifying the period for the fast EMA.
#' @param ema_slow_param Integer specifying the period for the slow EMA.
#' @param lag Integer specifying the lag for Hold state, default is 1.
#'
#' @return An xts object that includes the original stock data, Ema_fast, Ema_slow, Signal, Execution and Hold.
#'
#' @examples
#' # Example usage:
#' # stock_data should be an xts object with a 'Close' column
#' result <- apply_ema_crossover_buysell_engine(stock_data, 12, 26)
#'
#' @export
#'
apply_ema_crossover_buysell_engine <- function(stock_data, ema_fast_param, ema_slow_param, lag = 1){

  # Create indicators
  Ema_slow = comp_ema(stock_data[, "Close"], ema_slow_param)
  Ema_fast = comp_ema(stock_data[, "Close"], ema_fast_param)

  # Add Signal
  Signal <- rep(0, length(Ema_fast))

  # Add dummy
  dummy = rep(0, length(Ema_fast))

  for (i in 2:length(Ema_fast)) {

    if(Ema_fast[i] > Ema_slow[i]){

      if(Ema_fast[i-1] < Ema_slow[i-1] || Ema_fast[i-1] == Ema_slow[i-1]){
        Signal[i] <- 1
      }
    }else if(Ema_fast[i] < Ema_slow[i]){

      if(Ema_fast[i-1] > Ema_slow[i-1] || Ema_fast[i-1] == Ema_slow[i-1]){
        Signal[i] <- -1
      }
    }

  }

  # Add Hold
  Hold <- rep(0, NROW(stock_data))
  for (i in 2:NROW(stock_data)) {
    if (Signal[i] == 1) {
      Hold[i] <- 1
    } else if (Signal[i] == -1) {
      Hold[i] <- 0
    } else {
      Hold[i] <- Hold[i - 1]
    }
  }

  # Add Lag of Hold
  Hold = Lag(Hold, lag)
  Hold[is.na(Hold)] = 0
  colnames(Hold) = "Hold"

  # Add Execution day
  Execution = Lag(Signal, lag)
  Execution[is.na(Execution)] = 0
  colnames(Execution) = "Execution"

  # Convert to xts
  Signal <- xts(Signal, order.by=index(stock_data))
  Execution <- xts(Execution, order.by=index(stock_data))
  Hold <- xts(Hold, order.by=index(stock_data))


  # Combine output
  output <- merge(stock_data, Ema_fast, Ema_slow ,Signal, Execution ,Hold)

  return(output)
}









# Buy sell engine
buysell_engine = apply_ema_crossover_buysell_engine(stock_data,
                                                    ema_fast_param = 3,
                                                    ema_slow_param = 13,
                                                    lag = 1)
# Get portfolio
portfolio_data  = comp_portfolio(stock_data,
                                 buysell_engine,
                                 initial_capital = 100000,
                                 cost_per_trade =  0.00,
                                 volatility_per_trade =  0.00155)

# Plot
chartSeries(buysell_engine$Close, name = "Stock Price",theme = "white")
addTA(buysell_engine$Ema_fast,type='l',lwd=2,col="skyblue",on=1)
addTA(buysell_engine$Ema_slow,type='l',lwd=2,col="darkblue",on=1)
addTA(buysell_engine$Close[which(buysell_engine$Execution == 1)], on = 1, lwd = 3, col = "darkgreen", type = "p")
addTA(buysell_engine$Close[which(buysell_engine$Execution == -1)], on = 1, lwd = 3, col = "red", type = "b")
addTA(buysell_engine$Hold, lwd = 2, col = "black", type = "l")
addTA(buysell_engine$Signal,type = 'b' , lwd = 2, col = "darkblue")




# Check the outcome
df = cbind(buysell_engine[,1],buysell_engine[,4:8], comp_ewma_volatility(stock_data,36),portfolio_data$transaction_data, portfolio_data$portfolio_data)

# Get return and normalize
system_ri = dailyReturn(portfolio_data$portfolio_data$Value)
base_ri = dailyReturn(stock_data$Close)
factor = (sd(base_ri, na.rm = TRUE) / sd(system_ri, na.rm = TRUE))
normalized_ri = system_ri * factor

# Number of round trades per year
number_of_round_trade = nrow(na.omit(portfolio_data$transaction_data[portfolio_data$transaction_data$Transaction !=0]))/ 8

# Plot
charts.PerformanceSummary(cbind(base_ri, system_ri, normalized_ri))
create_annual_performance_table(cbind(base_ri, system_ri, normalized_ri))
SharpeRatio.annualized(base_ri)
SharpeRatio.annualized(system_ri)
print(number_of_round_trade)
plot(portfolio_data$portfolio_data$Holding)
nrow(na.omit(portfolio_data$transaction_data[portfolio_data$transaction_data$Transaction !=0]))


